# A copy-paste config to get a dev server up and running immediately.
Address: http://myserver.local
DaemonInterval: 10

Plugins: 
-   Key: Postgres
    Path: Wbtb.Extensions.Data.Postgres
    Config:
    -   User: postgres
    -   Host: <IP>
    -   Password: <PWD>
    -   Database: <DB>
-   Key: jenkinsSandbox
    Path : Wbtb.Extensions.BuildServer.JenkinsSandbox
-   Key: p4Sandbox
    Path: Wbtb.Extensions.SourceServer.PerforceSandbox
-   Key: CppParser
    Path: Wbtb.Extensions.LogParsing.Cpp
-   Key: BasicErrors
    Path: Wbtb.Extensions.LogParsing.BasicErrors
-   Key: myslack
    Path: Wbtb.Extensions.Messaging.SlackSandbox
    Config:
    -   Token: mytoken
-   Key: UnrealParser
    Path: Wbtb.Extensions.LogParsing.Unreal
-   Key: JenkinsSelfFailing
    Path: Wbtb.Extensions.LogParsing.JenkinsSelfFailing
-   Key: JenkinsBlamer
    Path: Wbtb.Extensions.PostProcessing.JenkinsSelfFailing
-   Key: Blamer
    Path: Wbtb.Extensions.PostProcessing.AcmeGamesBlamer

Users:
-   Key: Ug
    SourceServerIdentities:
    -   SourceServerKey: myperforce
        Name: Ug
-   Key: Mort
    SourceServerIdentities:
    -   SourceServerKey: myperforce
        Name: Mort
Groups:
  - Key: mygroup
    Message:
    -   Plugin: myslack
        SlackId: myslackchannelid
        IsGroup: true

SourceServers:
-   Key: myperforce
    Plugin: p4Sandbox

BuildServers:
-   Key: MyJenkins
    Plugin: jenkinsSandbox
    Jobs:
    -   Key: 248445e2
        Name: Ironbird
        RevisionAtBuildRegex: <current-revision>([\s\S]*?)<current-revision>
        SourceServer: myperforce
        Config: 
        -   RemoteKey: Project_Ironbird
        LogParsers: 
        -   UnrealParser 
        -   CppParser
        -   JenkinsSelfFailing
        -   BasicErrors
        PostProcessors:
        -   Blamer
        -   JenkinsBlamer
        Message:
        -   Plugin: myslack
            Group: mygroup
    -   Key: a967dfaaf967
        Name : SkunkWords
        RevisionAtBuildRegex : <current-revision>([\s\S]*?)<current-revision>
        SourceServer: myperforce
        Config: 
        -   RemoteKey: Project_Skunkwords
        LogParsers: 
        -   UnrealParser
        -   CppParser
        -   JenkinsSelfFailing
        -   BasicErrors
        PostProcessors:
        -   Blamer
        -   JenkinsBlamer
        Message:
        -   Plugin: myslack
            Group: mygroup