# A copy-paste config to get a dev server up and running immediately. Set env vars with .env in Wbtb.Core.Web directory
Address: {{env.WBTB_HOSTNAME}}
MaxThreads: {{env.WBTB_MAX_THREADS}}
DaemonInterval: {{env.WBTB_DAEMON_INTERVAL}}

Plugins: 
-   Key: Postgres
    Path: Wbtb.Extensions.Data.Postgres
    Config:
    -   User: {{env.PG_USER}}
    -   Host: {{env.PG_HOST}}
    -   Password: {{env.PG_ADMIN_PWD}}
    -   Database: {{env.PG_DATABASE}}
    -   MaxConnections: 2
-   Key: jenkinsSandbox
    Path : Wbtb.Extensions.BuildServer.JenkinsSandbox
-   Key: p4Sandbox
    Path: Wbtb.Extensions.SourceServer.PerforceSandbox
-   Key: CppParser
    Path: Wbtb.Extensions.LogParsing.Cpp
    Config:
    -   SectionDelimiter: "-- LOG SECTION:"
    -   MaxLineLength : 10000
-   Key: BasicErrors
    Path: Wbtb.Extensions.LogParsing.BasicErrors
-   Key: UnrealParser
    Path: Wbtb.Extensions.LogParsing.Unreal
    Config:
    -   SectionDelimiter: "-- LOG SECTION:"
    -   MaxLineLength : 10000
-   Key: NetworkSmokeTest
    Path: Wbtb.Extensions.LogParsing.SimpleRegex
    Custom:
        SectionDelimiter : "<delimiter>"
        Regex: "##Smoketest_error_alert##"
        Describes:
        -   Name : high ping
            Regex : Ping_error:(\d*)
        -   Name : time out
            Regex : Net_timeout:(\d*)
-   Key: NetworkSmokeTestBlamer
    Path: Wbtb.Extensions.PostProcessing.SimpleHooks
    Custom:
        KeyHook: NetworkSmokeTest
        Description: Network Smoke Test Failed
-   Key: JenkinsSelfFailing
    Path: Wbtb.Extensions.LogParsing.JenkinsSelfFailing
    Config:
    -   SectionDelimiter: "-- LOG SECTION:"
    -   MaxLineLength : 10000
-   Key: AcmeGamesTester
    Path: Wbtb.Extensions.LogParsing.AcmeGamesTester
    Config:
    -   SectionDelimiter: "-- LOG SECTION:"
    -   MaxLineLength : 10000
-   Key: myslack
    Path: Wbtb.Extensions.Messaging.SlackSandbox
    Config:
    -   Token: mytoken
-   Key: JenkinsBlamer
    Path: Wbtb.Extensions.PostProcessing.JenkinsSelfBlame
-   Key: Blamer
    Path: Wbtb.Extensions.PostProcessing.AcmeGamesBlamer

Users:
-   Key: Ug
    SourceServerIdentities:
    -   SourceServerKey: myperforce
        Name: Ug
-   Key: Mort
    SourceServerIdentities:
    -   SourceServerKey: myperforce
        Name: Mort
-   Key: Bob
    SourceServerIdentities:
    -   SourceServerKey: myperforce
        Name: Bob        
Groups:
  - Key: mygroup
    Message:
    -   Plugin: myslack
        SlackId: {{env.WBTB_SLACK_CHANNEL}}
        IsGroup: true

SourceServers:
-   Key: myperforce
    Plugin: p4Sandbox

JobGroups:
-   Key: myFailingJobGroup
    Jobs:
    -   248445e2
    -   a967dfaaf967
-   Key: myPassingJobGroup
    Jobs:
    -   a967dfaaf967

BuildServers:
-   Key: MyJenkins
    Plugin: jenkinsSandbox
    Config:
    -   Interval: 0 # jenkins-sandbox uses this to time-gate data
    Jobs:
    -   Key: 248445e2
        Name: Ironbird
        RevisionAtBuildRegex: <current-revision>([\s\S]*?)<current-revision>
        SourceServer: myperforce
        Config: 
        -   RemoteKey: Project_Ironbird
        -   GameRoot: //mydepot/main/core/PSD/Game
        -   Interval: 0 # jenkins-sandbox uses this to time-gate data
        LogParsers: 
        -   UnrealParser 
        -   CppParser
        -   NetworkSmokeTest 
        -   JenkinsSelfFailing
        -   BasicErrors
        -   AcmeGamesTester
        PostProcessors:
        -   JenkinsBlamer
        -   NetworkSmokeTestBlamer
        -   Blamer
        Message:
        -   Plugin: myslack
            Group: mygroup
        -   Plugin: myslack
            Group: mygroup
            Remind: 1
    -   Key: a967dfaaf967
        Name : SkunkWords
        RevisionAtBuildRegex : <current-revision>([\s\S]*?)<current-revision>
        SourceServer: myperforce
        Config: 
        -   RemoteKey: Project_Skunkwords
        -   Interval: 0 # jenkins-sandbox uses this to time-gate data
        LogParsers: 
        -   UnrealParser
        -   CppParser
        -   JenkinsSelfFailing
        -   BasicErrors
        -   AcmeGamesTester
        PostProcessors:
        -   JenkinsBlamer
        Message:
        -   Plugin: myslack
            Group: mygroup