# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "generic/ubuntu1604"
    config.vm.hostname = "whobrokethebuild"
    config.vm.synced_folder "./../..", "/vagrant", type: "nfs"
    config.vm.provision :shell, path: "./../provision.sh"

        # Note that in hyperV, you cannot access a guest via localhost:4050, 
    # use "ip address" to get machine address, it will be available at this
    config.vm.network "forwarded_port", guest: 3000, host: 3000
    config.vm.network "forwarded_port", guest: 3001, host: 3001
    config.vm.network "forwarded_port", guest: 3003, host: 3003
    # test instance in container
    config.vm.network "forwarded_port", guest: 4000, host: 4000
    # for mongo admin
    config.vm.network "forwarded_port", guest: 3002, host: 3002
    config.vm.network "forwarded_port", guest: 27017, host: 27018
    # for postgres admin
    config.vm.network "forwarded_port", guest: 3111, host: 3111
    # postgres
    config.vm.network "forwarded_port", guest: 5432, host: 5433
    # for jenkins
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    # for gitlab
    config.vm.network "forwarded_port", guest: 8081, host: 8081


    config.vm.provider :libvirt do |v|
        v.default_prefix = "whobrokethebuild"
    end

  end
