name: builds 
on: 
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: builds
        run: cd build && sh ./build.sh --ci --dockerpush
        env:
            DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
            DOCKER_USER: ${{ secrets.DOCKER_USER }}
