name: builds 
on: 
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: builds container and pushes to container repo
        run: |
            cd build/docker 
            sh ./build.sh --test --push
        env:
            DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
            DOCKER_USER: ${{ secrets.DOCKER_USER }}
